version: "3.8"

services:
  log-cmdline:
    image: '${DOCKER_IMAGE_PREFIX?Variable not set}barklan/log-cmdline:rolling'
    build:
      context: .
      dockerfile: dockerfiles/log-cmdline.dockerfile
      args:
        DOCKER_IMAGE_PREFIX: ${DOCKER_IMAGE_PREFIX?Variable not set}
    networks:
      - traefik-public
    env_file:
      - ./.env

networks:
  traefik-public:
    external: true
